version: '3.8'

services:
    airflow:
        container_name: airflow
        restart: unless-stopped
        build:
            context: ./airflow
            dockerfile: Dockerfile.airflow
            args:
              AIRFLOW_USERNAME: ${AIRFLOW_USERNAME:?AIRUSER blank}
              AIRFLOW_PASSWORD: ${AIRFLOW_PASSWORD:?AIRPASS blank}
        ports:
        - 127.0.0.1:8080:8080
        volumes:
        - ./dags:/root/airflow/dags
        - ./airflow/airflow.cfg:/root/airflow/airflow.cfg
        env_file:
        - .env
    jupyter:
        container_name: jupyter
        restart: unless-stopped
        image: jupyter/minimal-notebook:notebook-6.5.1
        ports:
        - 127.0.0.1:80:8888
        volumes:
        - ./dags:/home/jovyan/dags
        env_file: .env
    greenplum:
        container_name: greenplum
        restart: unless-stopped
        build:
          context: ./greenplum
          dockerfile: Dockerfile.greenplum
        #image: corvana/greenplum-oss:6.11.2
        networks:
            default:
                ipv4_address: 172.16.0.2
        ports:
        - 127.0.0.1:5432:5432
        command: [ "DATABASE_NAME=${DATABASE_NAME:?DBNAME blank}", "DATABASE_USER=${DATABASE_USER:?DBUSER blank}", "DATABASE_PASSWORD=${DATABASE_PASSWORD:?DBPASS blank}", "/gpdb/start-singlenode.sh"]
    zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper:7.2.1
      restart: unless-stopped
      env_file: .env
    kafka:
      container_name: kafka
      image: confluentinc/cp-kafka:7.2.1
      restart: unless-stopped
      networks:
        default:
          ipv4_address: 172.16.0.3
      env_file: .env
      ports:
        - 127.0.0.1:8098:8098
      depends_on:
        - zookeeper
networks:
    default:
        ipam:
            config:
                - subnet: '172.16.0.0/24'
