version: '3.8'

services:
  airflow:
    container_name: airflow
    restart: unless-stopped
    build:
      context: ./airflow
      dockerfile: Dockerfile.airflow
      args:
        AIRFLOW_USERNAME: ${AIRFLOW_USERNAME:?AIRUSER blank}
        AIRFLOW_PASSWORD: ${AIRFLOW_PASSWORD:?AIRPASS blank}
    networks:
      default:
        ipv4_address: 172.16.0.4
    ports:
      - 8080:8080
    volumes:
      - ./dags:/root/airflow/dags
      - ./airflow/airflow.cfg:/root/airflow/airflow.cfg
    env_file: .env

  jupyter:
    container_name: jupyter
    restart: unless-stopped
    image: jupyter/minimal-notebook:notebook-6.5.1
    ports:
      - 8888:8888
    volumes:
      - ./dags:/home/jovyan/dags
    env_file: .env
    networks:
      default:
        ipv4_address: 172.16.0.5

  greenplum:
    container_name: greenplum
    restart: unless-stopped
    build:
      context: ./greenplum
      dockerfile: Dockerfile.greenplum
    networks:
      default:
          ipv4_address: 172.16.0.2
    ports:
      - 5432:5432
    command: [ "DATABASE_NAME=${DATABASE_NAME:?DBNAME blank}", "DATABASE_USER=${DATABASE_USER:?DBUSER blank}", "DATABASE_PASSWORD=${DATABASE_PASSWORD:?DBPASS blank}", "/gpdb/start-singlenode.sh"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.8.0
    ports:
      - 2181:2181
    networks:
      default:
        ipv4_address: 172.16.0.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.3.1
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      default:
        ipv4_address: 172.16.0.3
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 5s
      retries: 1000
      start_period: 15s

networks:
  default:
    ipam:
      config:
        - subnet: '172.16.0.0/24'
